networks:
  default:
    external: true
    name: demo
services:
  map:
    command: -c "cd navigation && make map"
    environment:
    - FASTRTPS_DEFAULT_PROFILES_FILE=/home/ros2/fastrtps-profile.xml
    image: demo
    network_mode: host
    volumes:
    - .:/home/ros2
version: '3.8'
